# Generated by Django 5.2.4 on 2025-07-26 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_name'),
        ('deviceprofile', '0003_alter_deviceprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='deviceprofile.deviceprofile'),
        ),
    ]
