# Generated by Django 5.2.4 on 2025-07-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_asset_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='entity_type',
            field=models.CharField(default='ASSET', max_length=50),
        ),
    ]
