# Generated by Django 5.2.4 on 2025-07-26 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_name'),
        ('assetprofile', '0003_alter_assetprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assetprofile.assetprofile'),
        ),
    ]
