# Generated by Django 5.2.4 on 2025-07-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assetprofile',
            table='assetprofile',
        ),
    ]
