# Generated by Django 5.2.4 on 2025-07-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceprofile',
            table='deviceprofile',
        ),
    ]
